### ISSUE TITLE
Using site only VCF in create_gridss_pon.R

### ISSUE THREAD

**Issue by Griffan** [hartwigmedical/pipeline5#20]
I understand that create_gridss_pon.R expect input VCF files that contain specific individuals inside. If I only have a site-only PON vcf file, how can I use it directly here?
Thanks!

**Comment by pauldwolfe** [comment]
Hello Griffan, while pipeline5 uses gridss as a stage in tertiary processing, it is not where the scripts and software itself is maintained. Please have a look at https://github.com/PapenfussLab/gridss

**Comment by d-cameron** [comment]
@kduyvesteyn @pauldwolfe the underlying issue is that OP downloaded PON.vcf.gz instead of GRIDSS_PON_3792v1.zip from https://resources.hartwigmedicalfoundation.nl/

Is that the manta PON, or something else? We should stop sharing it if we're no longer actually using it.

**Comment by d-cameron** [comment]
We definitely shouldn't have the wrong file in the root directory, and the correct one in a subdirectory.

**Comment by pauldwolfe** [comment]
Hey guys, is this resolved? Regardless this is not the correct project for this issue.
