### ISSUE TITLE
How to run pipeline5 using docker.

### ISSUE THREAD

**Issue by senzhaocode** [hartwigmedical/pipeline5#261]
Hi developer,

Now I have pulled docker container of pipeline5 from Docker Hub: `docker pull hartwigmedicalfoundation/pipeline5:latest`
I could not find out a documentation and show an example. Here, I tried:

sudo docker run -t --rm -v /data/admsenzha/pipeline5 hartwigmedicalfoundation/pipeline5:latest 
<img width="1322" alt="Screenshot 2021-03-16 at 15 57 07" src="https://user-images.githubusercontent.com/26706345/111330503-49599980-8670-11eb-852e-0adae3231476.png">

It seems that the configuration is not correct? Not sure how to set input and configuration?

Sen

**Comment by pauldwolfe** [comment]
Hi Sen,
Running the docker container locally as you are typing to do is not supported. This container is meant to run within our own kubernetes cluster and has all sorts of coupling to our internal infrastructure.

If you'd like to run an HMF pipeline yourself please have a look at https://github.com/hartwigmedical/platinum. 

Cheers,
Paul

**Comment by senzhaocode** [comment]
Thank you for the reply. Yes, we would like to run pipeline5 in our local HPC. We have downloaded it and tired to build a docker container on basis of our environment, but not successfully. It seems the pipeline5 needs Google Cloud Platform as prerequisite. We just wonder are there any options to install and run pipeline5 independent of Google Cloud Platform.

**Comment by pauldwolfe** [comment]
At this point pipeline5 only runs on GCP. Did you want to run all the way from FASTQ? I believe there are some CWL + docker implementations for the calling and other tertiary algos you might be able to use..

**Comment by senzhaocode** [comment]
Yes, we would like to run the pipeline from raw FASTQ locally. We note that all analysis modules (e.g. amber, bachelor, sage...) in the pipeline virtually come from [hmftools](https://github.com/hartwigmedical/hmftools). Are there any pre-built docker containers for **hmftools** available, as we could not find something related to it on Docker Hub.

**Comment by pauldwolfe** [comment]
No we don't have any docker containers we support for the individual hmftools. They are all very simple JAR (with dependencies) based Java applications, so rolling them into containers should be straightforward. I would recommend just doing that yourself, its probably only a day or two of work.

**Comment by pauldwolfe** [comment]
I'm going to close this issue in the meantime, please reach out if you have any other questions
